In [7]:
#create two simple dataframes to work

import pandas as pd
df1=pd.DataFrame({
    'name': ['badal','barsha','bijuli'],
    'age': [23,25,30],
    'city': ['nepal','asurkot','nagarkot']

        })
df2 = pd.DataFrame({
    'Name': ['badal','barsha','bijuli'],
    'Age': [23, 24, 30],
    'City': ['nepal', 'asurkot', 'bhaktapur']
})


print(df1)
print(df2)


#checks are these data frames are completely identical or not.
df1.equals(df2) #it simply gives true or false value.

     name  age      city
0   badal   23     nepal
1  barsha   25   asurkot
2  bijuli   30  nagarkot
     Name  Age       City
0   badal   23      nepal
1  barsha   24    asurkot
2  bijuli   30  bhaktapur

False

In [11]:
import pandas as pd
df1=pd.DataFrame({
    'name': ['badal','barsha','bijuli'],
    'age': [23,25,30],
    'city': ['nepal','asurkot','nagarkot']

        })
df2 = pd.DataFrame({
    'name': ['badal','barsha','bijuli'],
    'age': [23, 24, 30],
    'city': ['nepal', 'asurkot', 'bhaktapur']
})

df1 == df2  # two dataframe ko each and every cell ko value compare garxa,if same xa vane true dinxa,if not false

   name    age   city
0  True   True   True
1  True  False   True
2  True   True  False

In [12]:
import pandas as pd
df1=pd.DataFrame({
    'name': ['badal','barsha','bijuli'],
    'age': [23,25,30],
    'city': ['nepal','asurkot','nagarkot']

        })
df2 = pd.DataFrame({
    'name': ['badal','barsha','bijuli'],
    'age': [23, 24, 30],
    'city': ['nepal', 'asurkot', 'bhaktapur']
})

df1.compare(df2)

    age            city
   self other      self      other
1  25.0  24.0       NaN        NaN
2   NaN   NaN  nagarkot  bhaktapur